# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 88091bcc1082431bbd52d03b42156403ddfde967bd6605c62a80b06bfa34d91527d296e3341459bf49ddee203731ca553ca0935c245a8699633155e902eb9dda

test:
  secret_key_base: 20bf9aa204c954904cd5ea2ef370f3847a5521c860358f5b068d4ccfaa5bfb081199885388ca0120d7648d204a721a6c0a6daf9114291beafce0eb8f73f28f56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
