% require_relative "../test/rails_test_helper"

resources:
  - name: ci
    type: git
    source:
      uri: https://github.com/flavorjones/loofah-activerecord
      branch: master
      disable_ci_skip: true # always get the latest pipeline configuration
  - name: loofah-activerecord
    type: git
    source:
      uri: https://github.com/flavorjones/loofah-activerecord
      branch: master
      ignore_paths:
        - concourse/**

jobs:
  - name: "unit"
    public: true
    plan:
      - get: ci
      - get: loofah-activerecord
        trigger: true
% Concourse::production_rubies.each do |ruby_version|
      - task: rake-test-<%= ruby_version.split(".").first(2).join(".") %>
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs: [{name: ci}, {name: loofah-activerecord}]
          params:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
          run:
            path: ci/concourse/tasks/rake-test/run.sh
% end

  - name: "rails"
    public: true
    plan:
      - get: ci
      - get: loofah-activerecord
        trigger: true
        passed: ["unit"]
% Loofah::RailsTests::VERSIONS.each do |version|
% short = version.split(".").first(2).join(".")
% ruby_version = Loofah::RailsTests::RAILS_TO_RUBY_VERSIONS[short]
      - task: rake-test-rails-<%= short %>
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: ruby, tag: "<%= ruby_version %>"}
          inputs: [{name: ci}, {name: loofah-activerecord}]
          params:
            NOKOGIRI_USE_SYSTEM_LIBRARIES: t
            TEST_RAILS_VERSION: <%= version %>
          run:
            path: ci/concourse/tasks/rake-test-rails/run.sh
% end
