# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19bfcc0f7600a02b2fc88005f47b7d2eba5ab7734f0deb2af0c2b3b58003480623297ca2a2b8ee25b7fbe0b4a1a7822b5bec33f1eb943ecbdca9583dc0afcbd6

test:
  secret_key_base: 25bd71c615a63223cf874a9bdb04a44bb280c7985b11fbcc6a4180f6bd27e7f43fd7130dff34b73e9b0cb3ea4be3132ff0b6d94a3e968e5f71c4bf162fec5b90

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
